### ISSUE TITLE
Missing test data

### ISSUE THREAD

**Issue by shubhamjha97** [HsinYingLee/OPN#8]
The test data has not been included in your project page. Can you please provide links to the test data matrices for the UCF and HMDB datasets?

**Comment by HsinYingLee** [comment]
@shubhamjha97 The train/test splits are the same as the original UCF and HMDB splits. For evaluation, it's just simple classification accuracy. The pipeline follows the standard evaluation protocal: given a video, sample 25 frames, 10 crops (four corners+center&flip) for each frame
